INSERT INTO entity_keywords (entity_code, lang_code, keyword, normalized_keyword, notes) VALUES
('speed', 'id', '10 mbps', '10 mbps', NULL),
('speed', 'id', '20 mbps', '20 mbps', NULL),
('speed', 'id', '30 mbps', '30 mbps', NULL),
('speed', 'id', '50 mbps', '50 mbps', NULL),
('speed', 'id', '100 mbps', '100 mbps', NULL),
('speed', 'id', '1 gbps', '1 gbps', NULL),
('speed', 'id', '10 mega', '10 mbps', 'Colloquial'),
('speed', 'id', '20 mega', '20 mbps', 'Colloquial'),
('speed', 'id', '30 mega', '30 mbps', 'Colloquial'),
('speed', 'id', '50 mega', '50 mbps', 'Colloquial'),
('payment_method', 'id', 'transfer bank', 'bank_transfer', NULL),
('payment_method', 'id', 'transfer', 'bank_transfer', NULL),
('payment_method', 'id', 'qris', 'qris', NULL),
('payment_method', 'id', 'cash', 'cash', NULL),
('payment_method', 'id', 'tunai', 'cash', NULL),
('payment_method', 'id', 'virtual account', 'virtual_account', NULL),
('payment_method', 'id', 'e-wallet', 'e_wallet', NULL),
('payment_method', 'id', 'gopay', 'gopay', NULL),
('payment_method', 'id', 'ovo', 'ovo', NULL),
('payment_method', 'id', 'dana', 'dana', NULL),

('router', 'id', 'modem', 'modem', NULL),
('router', 'id', 'router', 'router', NULL),
('router', 'id', 'wifi router', 'router', NULL),
('router', 'id', 'ont', 'ont', 'Fiber device'),
('router', 'id', 'perangkat wifi', 'router', NULL),

('schedule_time', 'id', 'pagi', 'morning', NULL),
('schedule_time', 'id', 'siang', 'afternoon', NULL),
('schedule_time', 'id', 'sore', 'evening', NULL),
('schedule_time', 'id', 'malam', 'night', NULL),
('schedule_time', 'id', 'jam 9', '09:00', NULL),
('schedule_time', 'id', 'jam 10', '10:00', NULL),
('schedule_time', 'id', 'jam 1 siang', '13:00', NULL),

('schedule_date', 'id', 'hari ini', 'today', NULL),
('schedule_date', 'id', 'besok', 'tomorrow', NULL),
('schedule_date', 'id', 'lusa', 'day_after_tomorrow', NULL),
('schedule_date', 'id', 'sabtu', 'saturday', NULL),
('schedule_date', 'id', 'minggu', 'sunday', NULL),
('schedule_date', 'id', 'weekday', 'weekday', NULL),
('schedule_date', 'id', 'weekend', 'weekend', NULL);
