INSERT INTO intents (intent_code, intent_name, description) VALUES
('ask_installation', 'Tanya pemasangan internet', 'Customer bertanya apakah bisa pasang internet rumah'),
('ask_package', 'Tanya paket internet', 'Customer menanyakan pilihan paket internet'),
('ask_price', 'Tanya harga', 'Customer menanyakan biaya langganan, promo, atau harga paket'),
('ask_coverage', 'Cek area jaringan', 'Customer ingin tahu apakah alamatnya tercover jaringan'),
('ask_speed', 'Tanya kecepatan internet', 'Customer menanyakan Mbps, stabilitas, upload/download'),
('ask_installation_fee', 'Tanya biaya pemasangan', 'Customer menanyakan biaya instalasi awal'),
('ask_installation_schedule', 'Tanya jadwal pemasangan', 'Customer ingin menentukan jadwal teknisi datang'),
('ask_payment_method', 'Tanya metode pembayaran', 'Customer menanyakan cara bayar'),
('ask_requirement', 'Tanya syarat pemasangan', 'Customer menanyakan KTP, alamat, nomor HP, atau dokumen'),
('ask_promo', 'Tanya promo', 'Customer mencari diskon atau promo pemasangan'),
('ask_contract', 'Tanya kontrak', 'Customer menanyakan masa kontrak atau penalti berhenti'),
('ask_router', 'Tanya modem/router', 'Customer menanyakan perangkat yang diberikan'),
('ask_availability_today', 'Tanya pemasangan cepat', 'Customer ingin dipasang hari ini atau secepatnya'),
('compare_package', 'Membandingkan paket', 'Customer membandingkan paket berdasarkan harga/kecepatan'),
('choose_package', 'Memilih paket', 'Customer menyatakan ingin mengambil paket tertentu'),
('provide_address', 'Memberikan alamat', 'Customer memberikan alamat untuk cek jaringan/pemasangan'),
('provide_contact', 'Memberikan kontak', 'Customer memberikan nomor HP/nama'),
('confirm_order', 'Konfirmasi pemasangan', 'Customer menyetujui pemasangan'),
('cancel_order', 'Membatalkan pemasangan', 'Customer membatalkan atau menunda pemasangan'),
('complaint_installation', 'Komplain pemasangan', 'Customer komplain teknisi belum datang atau pemasangan bermasalah'),
('follow_up_installation', 'Follow-up pemasangan', 'Customer menanyakan status pemasangan'),
('negotiate_price', 'Negosiasi harga', 'Customer menawar harga atau meminta diskon'),
('ask_after_sales', 'Tanya layanan setelah pemasangan', 'Customer bertanya support, gangguan, atau customer service'),
('greeting', 'Sapaan awal', 'Customer membuka percakapan'),
('thanks', 'Ucapan terima kasih', 'Customer mengucapkan terima kasih'),
('unknown', 'Tidak diketahui', 'Kalimat tidak jelas atau di luar konteks');