INSERT INTO keywords (intent_code, lang_code, keyword, normalized_keyword, formality_level, weight, notes) VALUES
('ask_installation', 'id', 'mau pasang internet', 'pasang internet', 'informal', 5, 'High intent'),
('ask_installation', 'id', 'ingin pasang wifi', 'pasang wifi', 'semi_formal', 5, 'High intent'),
('ask_installation', 'id', 'bisa pasang internet rumah?', 'pasang internet rumah', 'informal', 5, 'Direct inquiry'),
('ask_installation', 'id', 'saya mau daftar internet rumah', 'daftar internet rumah', 'formal', 5, 'Registration intent'),
('ask_installation', 'id', 'cara pasang wifi di rumah', 'cara pasang wifi rumah', 'informal', 4, 'Question format'),
('ask_installation', 'id', 'mau langganan internet', 'langganan internet', 'informal', 5, 'Subscription intent'),
('ask_installation', 'id', 'saya ingin berlangganan internet', 'berlangganan internet', 'formal', 5, 'Subscription intent'),
('ask_installation', 'id', 'ada layanan internet rumah?', 'layanan internet rumah', 'semi_formal', 4, 'Service availability'),
('ask_installation', 'id', 'bisa daftar wifi?', 'daftar wifi', 'informal', 5, 'Short informal'),
('ask_installation', 'id', 'saya tertarik pasang internet', 'tertarik pasang internet', 'formal', 4, 'Soft intent');
INSERT INTO keywords (intent_code, lang_code, keyword, normalized_keyword, formality_level, weight, notes) VALUES
('ask_package', 'id', 'ada paket apa saja?', 'paket tersedia', 'informal', 5, NULL),
('ask_package', 'id', 'paket internetnya apa saja?', 'paket internet', 'informal', 5, NULL),
('ask_package', 'id', 'pilihan paket internet', 'pilihan paket internet', 'semi_formal', 4, NULL),
('ask_package', 'id', 'paket wifi rumah', 'paket wifi rumah', 'informal', 4, NULL),
('ask_package', 'id', 'minta info paket', 'info paket', 'informal', 5, NULL),
('ask_package', 'id', 'boleh lihat daftar paket?', 'daftar paket', 'semi_formal', 4, NULL),
('ask_package', 'id', 'paket paling murah apa?', 'paket murah', 'informal', 5, NULL),
('ask_package', 'id', 'paket untuk rumah ada apa saja?', 'paket rumah', 'semi_formal', 5, NULL),
('ask_package', 'id', 'paket unlimited ada?', 'paket unlimited', 'informal', 4, NULL),
('ask_package', 'id', 'paket keluarga ada?', 'paket keluarga', 'informal', 3, NULL);
INSERT INTO keywords (intent_code, lang_code, keyword, normalized_keyword, formality_level, weight, notes) VALUES
('ask_price', 'id', 'berapa harganya?', 'harga', 'informal', 5, NULL),
('ask_price', 'id', 'harga paket internet', 'harga paket internet', 'semi_formal', 5, NULL),
('ask_price', 'id', 'biaya bulanannya berapa?', 'biaya bulanan', 'informal', 5, NULL),
('ask_price', 'id', 'tarif per bulan', 'tarif bulanan', 'formal', 4, NULL),
('ask_price', 'id', 'langganannya berapa sebulan?', 'langganan bulanan', 'informal', 5, NULL),
('ask_price', 'id', 'ada harga promo?', 'harga promo', 'informal', 4, NULL),
('ask_price', 'id', 'total biaya awal berapa?', 'biaya awal', 'semi_formal', 5, NULL),
('ask_price', 'id', 'berapa biaya internet rumah?', 'biaya internet rumah', 'semi_formal', 5, NULL),
('ask_price', 'id', 'paket 20 mbps berapa?', 'harga speed', 'informal', 5, 'Contains speed entity'),
('ask_price', 'id', 'harga sudah termasuk modem?', 'harga termasuk modem', 'semi_formal', 4, NULL);
INSERT INTO keywords (intent_code, lang_code, keyword, normalized_keyword, formality_level, weight, notes) VALUES
('ask_coverage', 'id', 'area saya tercover?', 'cek coverage', 'informal', 5, NULL),
('ask_coverage', 'id', 'cek jaringan di alamat saya', 'cek jaringan alamat', 'semi_formal', 5, NULL),
('ask_coverage', 'id', 'apakah daerah saya sudah masuk jaringan?', 'coverage daerah', 'formal', 5, NULL),
('ask_coverage', 'id', 'di lokasi saya bisa pasang?', 'lokasi bisa pasang', 'informal', 5, NULL),
('ask_coverage', 'id', 'coverage di Bandung ada?', 'coverage area', 'informal', 4, 'Area entity'),
('ask_coverage', 'id', 'jaringan sudah sampai sini belum?', 'jaringan tersedia', 'informal', 5, NULL),
('ask_coverage', 'id', 'alamat saya bisa dipasang internet?', 'alamat bisa pasang', 'semi_formal', 5, NULL),
('ask_coverage', 'id', 'cek coverage dulu', 'cek coverage', 'informal', 5, NULL),
('ask_coverage', 'id', 'di komplek saya sudah ada jaringan?', 'coverage komplek', 'informal', 4, NULL),
('ask_coverage', 'id', 'apakah layanan tersedia di wilayah saya?', 'layanan tersedia wilayah', 'formal', 5, NULL);
INSERT INTO keywords (intent_code, lang_code, keyword, normalized_keyword, formality_level, weight, notes) VALUES
('ask_installation_schedule', 'id', 'kapan bisa dipasang?', 'jadwal pemasangan', 'informal', 5, NULL),
('ask_installation_schedule', 'id', 'jadwal teknisi kapan?', 'jadwal teknisi', 'informal', 5, NULL),
('ask_installation_schedule', 'id', 'bisa pasang hari ini?', 'pasang hari ini', 'informal', 5, 'Urgent'),
('ask_installation_schedule', 'id', 'pemasangan bisa besok?', 'pasang besok', 'informal', 5, NULL),
('ask_installation_schedule', 'id', 'saya ingin jadwalkan pemasangan', 'jadwalkan pemasangan', 'formal', 5, NULL),
('ask_installation_schedule', 'id', 'teknisi bisa datang jam berapa?', 'jam teknisi datang', 'semi_formal', 5, NULL),
('ask_installation_schedule', 'id', 'berapa lama proses pemasangan?', 'durasi pemasangan', 'semi_formal', 4, NULL),
('ask_installation_schedule', 'id', 'estimasi pemasangan berapa hari?', 'estimasi pemasangan', 'semi_formal', 4, NULL),
('ask_installation_schedule', 'id', 'bisa request jadwal?', 'request jadwal', 'informal', 4, NULL),
('ask_installation_schedule', 'id', 'saya available hari sabtu', 'available schedule', 'semi_formal', 4, NULL);
INSERT INTO keywords (intent_code, lang_code, keyword, normalized_keyword, formality_level, weight, notes) VALUES
('ask_payment_method', 'id', 'bayarnya gimana?', 'cara bayar', 'informal', 5, NULL),
('ask_payment_method', 'id', 'metode pembayaran apa saja?', 'metode pembayaran', 'formal', 5, NULL),
('ask_payment_method', 'id', 'bisa bayar transfer?', 'bayar transfer', 'informal', 5, NULL),
('ask_payment_method', 'id', 'bisa bayar cash?', 'bayar cash', 'informal', 5, NULL),
('ask_payment_method', 'id', 'ada qris?', 'qris', 'informal', 4, NULL),
('ask_payment_method', 'id', 'pembayaran lewat virtual account bisa?', 'virtual account', 'formal', 4, NULL),
('ask_payment_method', 'id', 'bayar setelah terpasang?', 'bayar setelah pasang', 'informal', 5, NULL),
('ask_payment_method', 'id', 'harus bayar dulu?', 'bayar dulu', 'informal', 5, NULL),
('ask_payment_method', 'id', 'tagihan dibayar ke mana?', 'bayar tagihan', 'semi_formal', 4, NULL),
('ask_payment_method', 'id', 'bisa pakai e-wallet?', 'e-wallet', 'informal', 4, NULL);
INSERT INTO keywords (intent_code, lang_code, keyword, normalized_keyword, formality_level, weight, notes) VALUES
('ask_installation', 'su', 'abdi hoyong pasang internet', 'pasang internet', 'formal', 5, 'Sundanese polite'),
('ask_installation', 'su', 'rek masang wifi di bumi', 'pasang wifi rumah', 'informal', 5, 'Mixed informal'),
('ask_installation', 'su', 'bisa pasang wifi di imah?', 'pasang wifi rumah', 'informal', 5, 'Common mixed'),
('ask_installation', 'su', 'abdi bade langganan internet', 'langganan internet', 'formal', 5, NULL),
('ask_installation', 'su', 'hoyong daftar internet bumi', 'daftar internet rumah', 'semi_formal', 5, NULL),
('ask_installation', 'su', 'aya layanan internet kanggo bumi?', 'layanan internet rumah', 'semi_formal', 4, NULL),
('ask_installation', 'su', 'kumaha carana masang wifi?', 'cara pasang wifi', 'informal', 4, NULL),
('ask_installation', 'su', 'abdi minat pasang internet', 'minat pasang internet', 'formal', 4, NULL),
('ask_installation', 'su', 'di bumi abdi tiasa dipasang wifi?', 'rumah bisa pasang wifi', 'formal', 5, NULL),
('ask_installation', 'su', 'rek daftar wifi kang', 'daftar wifi', 'informal', 5, 'Very common sales chat');
INSERT INTO keywords (intent_code, lang_code, keyword, normalized_keyword, formality_level, weight, notes) VALUES
('ask_package', 'su', 'paketna aya naon wae?', 'paket tersedia', 'informal', 5, NULL),
('ask_package', 'su', 'aya paket internet naon wae?', 'paket internet tersedia', 'semi_formal', 5, NULL),
('ask_package', 'su', 'muhun, paket wifi na naon wae?', 'paket wifi tersedia', 'semi_formal', 5, NULL),
('ask_package', 'su', 'paket anu paling mirah naon?', 'paket murah', 'informal', 5, NULL),
('ask_package', 'su', 'abdi tiasa ningali daftar paket?', 'daftar paket', 'formal', 4, NULL),
('ask_package', 'su', 'paket kanggo bumi aya?', 'paket rumah', 'semi_formal', 4, NULL),
('ask_package', 'su', 'aya paket unlimited?', 'paket unlimited', 'informal', 4, NULL),
('ask_package', 'su', 'paket 20 mega aya?', 'paket speed', 'informal', 4, 'Speed entity'),
('ask_package', 'su', 'paket keluarga aya teu?', 'paket keluarga', 'informal', 3, NULL),
('ask_package', 'su', 'minta info paketna kang', 'info paket', 'informal', 5, 'Mixed');
INSERT INTO keywords (intent_code, lang_code, keyword, normalized_keyword, formality_level, weight, notes) VALUES
('ask_price', 'su', 'sabaraha hargana?', 'harga', 'informal', 5, NULL),
('ask_price', 'su', 'biayana sabaraha?', 'biaya', 'semi_formal', 5, NULL),
('ask_price', 'su', 'sabulan sabaraha?', 'biaya bulanan', 'informal', 5, NULL),
('ask_price', 'su', 'tarif per bulan sabaraha?', 'tarif bulanan', 'semi_formal', 4, NULL),
('ask_price', 'su', 'harga paketna sabaraha?', 'harga paket', 'informal', 5, NULL),
('ask_price', 'su', 'aya promo harga?', 'harga promo', 'informal', 4, NULL),
('ask_price', 'su', 'biaya awalna sabaraha?', 'biaya awal', 'semi_formal', 5, NULL),
('ask_price', 'su', 'pemasangan kedah mayar sabaraha?', 'biaya pemasangan', 'formal', 5, NULL),
('ask_price', 'su', 'paket 30 mbps sabaraha?', 'harga speed', 'informal', 5, NULL),
('ask_price', 'su', 'harga tos kaasup modem?', 'harga termasuk modem', 'semi_formal', 4, NULL);
INSERT INTO keywords (intent_code, lang_code, keyword, normalized_keyword, formality_level, weight, notes) VALUES
('ask_coverage', 'su', 'di daerah abdi tos aya jaringan?', 'coverage daerah', 'formal', 5, NULL),
('ask_coverage', 'su', 'alamat abdi tiasa dipasang?', 'alamat bisa pasang', 'formal', 5, NULL),
('ask_coverage', 'su', 'di imah abdi bisa pasang wifi?', 'rumah bisa pasang wifi', 'semi_formal', 5, NULL),
('ask_coverage', 'su', 'cek jaringan di alamat ieu', 'cek jaringan alamat', 'informal', 5, NULL),
('ask_coverage', 'su', 'daerah abdi ka-cover teu?', 'coverage area', 'informal', 5, 'Mixed'),
('ask_coverage', 'su', 'di komplek abdi tos aya jaringan?', 'coverage komplek', 'semi_formal', 4, NULL),
('ask_coverage', 'su', 'jaringan tos dugi ka dieu acan?', 'jaringan tersedia', 'informal', 5, NULL),
('ask_coverage', 'su', 'wilayah ieu tiasa dipasang internet?', 'wilayah bisa pasang', 'semi_formal', 5, NULL),
('ask_coverage', 'su', 'kanggo alamat ieu aya coverage?', 'coverage alamat', 'semi_formal', 5, NULL),
('ask_coverage', 'su', 'bisa cek coverage heula?', 'cek coverage', 'informal', 5, 'Mixed');
INSERT INTO keywords (intent_code, lang_code, keyword, normalized_keyword, formality_level, weight, notes) VALUES
('ask_installation', 'en', 'I want to install home internet', 'install home internet', 'formal', 5, NULL),
('ask_installation', 'en', 'can I install wifi at home?', 'install wifi home', 'informal', 5, NULL),
('ask_installation', 'en', 'I would like to subscribe to home internet', 'subscribe home internet', 'formal', 5, NULL),
('ask_installation', 'en', 'how can I get wifi installed?', 'get wifi installed', 'semi_formal', 4, NULL),
('ask_installation', 'en', 'I want to register for internet service', 'register internet service', 'formal', 5, NULL),
('ask_installation', 'en', 'do you provide home internet?', 'provide home internet', 'semi_formal', 4, NULL),
('ask_installation', 'en', 'need wifi installation', 'wifi installation', 'informal', 5, NULL),
('ask_installation', 'en', 'can you install internet in my house?', 'install internet house', 'informal', 5, NULL),
('ask_installation', 'en', 'I am interested in your internet service', 'interested internet service', 'formal', 4, NULL),
('ask_installation', 'en', 'how do I apply for home broadband?', 'apply home broadband', 'formal', 5, NULL);
INSERT INTO keywords (intent_code, lang_code, keyword, normalized_keyword, formality_level, weight, notes) VALUES
('ask_package', 'en', 'what packages are available?', 'available packages', 'semi_formal', 5, NULL),
('ask_package', 'en', 'what internet plans do you have?', 'internet plans', 'informal', 5, NULL),
('ask_package', 'en', 'can I see the package list?', 'package list', 'semi_formal', 4, NULL),
('ask_package', 'en', 'do you have unlimited plans?', 'unlimited plans', 'informal', 4, NULL),
('ask_package', 'en', 'what is the cheapest package?', 'cheapest package', 'informal', 5, NULL),
('ask_package', 'en', 'home wifi package', 'home wifi package', 'informal', 4, NULL),
('ask_package', 'en', 'family internet package', 'family internet package', 'semi_formal', 3, NULL),
('ask_package', 'en', 'which plan is suitable for home use?', 'suitable home plan', 'semi_formal', 5, NULL),
('ask_package', 'en', 'do you have a gaming package?', 'gaming package', 'informal', 3, NULL),
('ask_package', 'en', 'please send me the internet package details', 'package details', 'formal', 5, NULL);
INSERT INTO keywords (intent_code, lang_code, keyword, normalized_keyword, formality_level, weight, notes) VALUES
('ask_price', 'en', 'how much is it?', 'price', 'informal', 5, NULL),
('ask_price', 'en', 'what is the monthly fee?', 'monthly fee', 'semi_formal', 5, NULL),
('ask_price', 'en', 'how much per month?', 'monthly price', 'informal', 5, NULL),
('ask_price', 'en', 'what is the subscription cost?', 'subscription cost', 'formal', 5, NULL),
('ask_price', 'en', 'is there any promo price?', 'promo price', 'informal', 4, NULL),
('ask_price', 'en', 'how much is the installation fee?', 'installation fee', 'semi_formal', 5, NULL),
('ask_price', 'en', 'what is the total upfront cost?', 'upfront cost', 'formal', 5, NULL),
('ask_price', 'en', 'does the price include the router?', 'price include router', 'semi_formal', 4, NULL),
('ask_price', 'en', 'how much for 30 mbps?', 'price speed', 'informal', 5, NULL),
('ask_price', 'en', 'are there any additional charges?', 'additional charges', 'formal', 4, NULL);
INSERT INTO keywords (intent_code, lang_code, keyword, normalized_keyword, formality_level, weight, notes) VALUES
('ask_coverage', 'en', 'is my area covered?', 'area coverage', 'informal', 5, NULL),
('ask_coverage', 'en', 'can you check coverage at my address?', 'check coverage address', 'semi_formal', 5, NULL),
('ask_coverage', 'en', 'is your network available in my area?', 'network available area', 'formal', 5, NULL),
('ask_coverage', 'en', 'can I install it at my location?', 'install location', 'informal', 5, NULL),
('ask_coverage', 'en', 'do you cover this address?', 'cover address', 'semi_formal', 5, NULL),
('ask_coverage', 'en', 'is there service in my neighborhood?', 'service neighborhood', 'semi_formal', 4, NULL),
('ask_coverage', 'en', 'can you check my address first?', 'check address', 'informal', 5, NULL),
('ask_coverage', 'en', 'is broadband available here?', 'broadband available', 'semi_formal', 4, NULL),
('ask_coverage', 'en', 'does your fiber network reach my house?', 'fiber network reach house', 'formal', 5, NULL),
('ask_coverage', 'en', 'coverage check please', 'coverage check', 'informal', 5, NULL);
