from __future__ import annotations

# Default intent/entity seed data for new SQLite databases.
# Keep this data in Python so production deployments do not need root .sql files.

DEFAULT_INTENT_SEED = {'intents': [{'intent_code': 'ask_installation',
              'intent_name': 'Tanya pemasangan internet',
              'description': 'Customer bertanya apakah bisa pasang internet rumah'},
             {'intent_code': 'ask_package',
              'intent_name': 'Tanya paket internet',
              'description': 'Customer menanyakan pilihan paket internet'},
             {'intent_code': 'ask_price',
              'intent_name': 'Tanya harga',
              'description': 'Customer menanyakan biaya langganan, promo, atau harga paket'},
             {'intent_code': 'ask_coverage',
              'intent_name': 'Cek area jaringan',
              'description': 'Customer ingin tahu apakah alamatnya tercover jaringan'},
             {'intent_code': 'ask_speed',
              'intent_name': 'Tanya kecepatan internet',
              'description': 'Customer menanyakan Mbps, stabilitas, upload/download'},
             {'intent_code': 'ask_installation_fee',
              'intent_name': 'Tanya biaya pemasangan',
              'description': 'Customer menanyakan biaya instalasi awal'},
             {'intent_code': 'ask_installation_schedule',
              'intent_name': 'Tanya jadwal pemasangan',
              'description': 'Customer ingin menentukan jadwal teknisi datang'},
             {'intent_code': 'ask_payment_method',
              'intent_name': 'Tanya metode pembayaran',
              'description': 'Customer menanyakan cara bayar'},
             {'intent_code': 'ask_requirement',
              'intent_name': 'Tanya syarat pemasangan',
              'description': 'Customer menanyakan KTP, alamat, nomor HP, atau dokumen'},
             {'intent_code': 'ask_promo',
              'intent_name': 'Tanya promo',
              'description': 'Customer mencari diskon atau promo pemasangan'},
             {'intent_code': 'ask_contract',
              'intent_name': 'Tanya kontrak',
              'description': 'Customer menanyakan masa kontrak atau penalti berhenti'},
             {'intent_code': 'ask_router',
              'intent_name': 'Tanya modem/router',
              'description': 'Customer menanyakan perangkat yang diberikan'},
             {'intent_code': 'ask_availability_today',
              'intent_name': 'Tanya pemasangan cepat',
              'description': 'Customer ingin dipasang hari ini atau secepatnya'},
             {'intent_code': 'compare_package',
              'intent_name': 'Membandingkan paket',
              'description': 'Customer membandingkan paket berdasarkan harga/kecepatan'},
             {'intent_code': 'choose_package',
              'intent_name': 'Memilih paket',
              'description': 'Customer menyatakan ingin mengambil paket tertentu'},
             {'intent_code': 'provide_address',
              'intent_name': 'Memberikan alamat',
              'description': 'Customer memberikan alamat untuk cek jaringan/pemasangan'},
             {'intent_code': 'provide_contact',
              'intent_name': 'Memberikan kontak',
              'description': 'Customer memberikan nomor HP/nama'},
             {'intent_code': 'confirm_order',
              'intent_name': 'Konfirmasi pemasangan',
              'description': 'Customer menyetujui pemasangan'},
             {'intent_code': 'cancel_order',
              'intent_name': 'Membatalkan pemasangan',
              'description': 'Customer membatalkan atau menunda pemasangan'},
             {'intent_code': 'complaint_installation',
              'intent_name': 'Komplain pemasangan',
              'description': 'Customer komplain teknisi belum datang atau pemasangan bermasalah'},
             {'intent_code': 'follow_up_installation',
              'intent_name': 'Follow-up pemasangan',
              'description': 'Customer menanyakan status pemasangan'},
             {'intent_code': 'negotiate_price',
              'intent_name': 'Negosiasi harga',
              'description': 'Customer menawar harga atau meminta diskon'},
             {'intent_code': 'ask_after_sales',
              'intent_name': 'Tanya layanan setelah pemasangan',
              'description': 'Customer bertanya support, gangguan, atau customer service'},
             {'intent_code': 'greeting',
              'intent_name': 'Sapaan awal',
              'description': 'Customer membuka percakapan'},
             {'intent_code': 'thanks',
              'intent_name': 'Ucapan terima kasih',
              'description': 'Customer mengucapkan terima kasih'},
             {'intent_code': 'unknown',
              'intent_name': 'Tidak diketahui',
              'description': 'Kalimat tidak jelas atau di luar konteks'}],
 'languages': [{'lang_code': 'id', 'lang_name': 'Bahasa Indonesia'},
               {'lang_code': 'su', 'lang_name': 'Bahasa Sunda'},
               {'lang_code': 'en', 'lang_name': 'English'}],
 'entities': [{'entity_code': 'package_name',
               'entity_name': 'Nama paket',
               'description': 'Nama paket internet seperti basic, family, gamer, corporate'},
              {'entity_code': 'speed',
               'entity_name': 'Kecepatan internet',
               'description': 'Kecepatan internet dalam Mbps/Gbps'},
              {'entity_code': 'price',
               'entity_name': 'Harga',
               'description': 'Harga paket atau biaya pemasangan'},
              {'entity_code': 'address',
               'entity_name': 'Alamat',
               'description': 'Alamat pemasangan customer'},
              {'entity_code': 'area',
               'entity_name': 'Area/wilayah',
               'description': 'Kota, kecamatan, desa, komplek, perumahan'},
              {'entity_code': 'schedule_date',
               'entity_name': 'Tanggal pemasangan',
               'description': 'Tanggal teknisi datang'},
              {'entity_code': 'schedule_time',
               'entity_name': 'Jam pemasangan',
               'description': 'Jam atau rentang waktu pemasangan'},
              {'entity_code': 'payment_method',
               'entity_name': 'Metode pembayaran',
               'description': 'Transfer, QRIS, cash, e-wallet, virtual account'},
              {'entity_code': 'customer_name',
               'entity_name': 'Nama customer',
               'description': 'Nama pelanggan'},
              {'entity_code': 'phone_number',
               'entity_name': 'Nomor HP',
               'description': 'Nomor telepon customer'},
              {'entity_code': 'id_card',
               'entity_name': 'KTP',
               'description': 'Data identitas customer'},
              {'entity_code': 'router',
               'entity_name': 'Router/modem',
               'description': 'Perangkat internet'},
              {'entity_code': 'installation_fee',
               'entity_name': 'Biaya instalasi',
               'description': 'Biaya pasang awal'},
              {'entity_code': 'promo',
               'entity_name': 'Promo',
               'description': 'Diskon, cashback, free installation'},
              {'entity_code': 'contract_duration',
               'entity_name': 'Durasi kontrak',
               'description': 'Masa berlangganan atau minimal kontrak'},
              {'entity_code': 'technician',
               'entity_name': 'Teknisi',
               'description': 'Petugas instalasi'},
              {'entity_code': 'problem',
               'entity_name': 'Masalah',
               'description': 'Kendala pemasangan atau jaringan'}],
 'keywords': [{'intent_code': 'ask_installation',
               'lang_code': 'id',
               'keyword': 'mau pasang internet',
               'normalized_keyword': 'pasang internet',
               'formality_level': 'informal',
               'weight': 5,
               'notes': 'High intent'},
              {'intent_code': 'ask_installation',
               'lang_code': 'id',
               'keyword': 'ingin pasang wifi',
               'normalized_keyword': 'pasang wifi',
               'formality_level': 'semi_formal',
               'weight': 5,
               'notes': 'High intent'},
              {'intent_code': 'ask_installation',
               'lang_code': 'id',
               'keyword': 'bisa pasang internet rumah?',
               'normalized_keyword': 'pasang internet rumah',
               'formality_level': 'informal',
               'weight': 5,
               'notes': 'Direct inquiry'},
              {'intent_code': 'ask_installation',
               'lang_code': 'id',
               'keyword': 'saya mau daftar internet rumah',
               'normalized_keyword': 'daftar internet rumah',
               'formality_level': 'formal',
               'weight': 5,
               'notes': 'Registration intent'},
              {'intent_code': 'ask_installation',
               'lang_code': 'id',
               'keyword': 'cara pasang wifi di rumah',
               'normalized_keyword': 'cara pasang wifi rumah',
               'formality_level': 'informal',
               'weight': 4,
               'notes': 'Question format'},
              {'intent_code': 'ask_installation',
               'lang_code': 'id',
               'keyword': 'mau langganan internet',
               'normalized_keyword': 'langganan internet',
               'formality_level': 'informal',
               'weight': 5,
               'notes': 'Subscription intent'},
              {'intent_code': 'ask_installation',
               'lang_code': 'id',
               'keyword': 'saya ingin berlangganan internet',
               'normalized_keyword': 'berlangganan internet',
               'formality_level': 'formal',
               'weight': 5,
               'notes': 'Subscription intent'},
              {'intent_code': 'ask_installation',
               'lang_code': 'id',
               'keyword': 'ada layanan internet rumah?',
               'normalized_keyword': 'layanan internet rumah',
               'formality_level': 'semi_formal',
               'weight': 4,
               'notes': 'Service availability'},
              {'intent_code': 'ask_installation',
               'lang_code': 'id',
               'keyword': 'bisa daftar wifi?',
               'normalized_keyword': 'daftar wifi',
               'formality_level': 'informal',
               'weight': 5,
               'notes': 'Short informal'},
              {'intent_code': 'ask_installation',
               'lang_code': 'id',
               'keyword': 'saya tertarik pasang internet',
               'normalized_keyword': 'tertarik pasang internet',
               'formality_level': 'formal',
               'weight': 4,
               'notes': 'Soft intent'},
              {'intent_code': 'ask_package',
               'lang_code': 'id',
               'keyword': 'ada paket apa saja?',
               'normalized_keyword': 'paket tersedia',
               'formality_level': 'informal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_package',
               'lang_code': 'id',
               'keyword': 'paket internetnya apa saja?',
               'normalized_keyword': 'paket internet',
               'formality_level': 'informal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_package',
               'lang_code': 'id',
               'keyword': 'pilihan paket internet',
               'normalized_keyword': 'pilihan paket internet',
               'formality_level': 'semi_formal',
               'weight': 4,
               'notes': None},
              {'intent_code': 'ask_package',
               'lang_code': 'id',
               'keyword': 'paket wifi rumah',
               'normalized_keyword': 'paket wifi rumah',
               'formality_level': 'informal',
               'weight': 4,
               'notes': None},
              {'intent_code': 'ask_package',
               'lang_code': 'id',
               'keyword': 'minta info paket',
               'normalized_keyword': 'info paket',
               'formality_level': 'informal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_package',
               'lang_code': 'id',
               'keyword': 'boleh lihat daftar paket?',
               'normalized_keyword': 'daftar paket',
               'formality_level': 'semi_formal',
               'weight': 4,
               'notes': None},
              {'intent_code': 'ask_package',
               'lang_code': 'id',
               'keyword': 'paket paling murah apa?',
               'normalized_keyword': 'paket murah',
               'formality_level': 'informal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_package',
               'lang_code': 'id',
               'keyword': 'paket untuk rumah ada apa saja?',
               'normalized_keyword': 'paket rumah',
               'formality_level': 'semi_formal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_package',
               'lang_code': 'id',
               'keyword': 'paket unlimited ada?',
               'normalized_keyword': 'paket unlimited',
               'formality_level': 'informal',
               'weight': 4,
               'notes': None},
              {'intent_code': 'ask_package',
               'lang_code': 'id',
               'keyword': 'paket keluarga ada?',
               'normalized_keyword': 'paket keluarga',
               'formality_level': 'informal',
               'weight': 3,
               'notes': None},
              {'intent_code': 'ask_price',
               'lang_code': 'id',
               'keyword': 'berapa harganya?',
               'normalized_keyword': 'harga',
               'formality_level': 'informal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_price',
               'lang_code': 'id',
               'keyword': 'harga paket internet',
               'normalized_keyword': 'harga paket internet',
               'formality_level': 'semi_formal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_price',
               'lang_code': 'id',
               'keyword': 'biaya bulanannya berapa?',
               'normalized_keyword': 'biaya bulanan',
               'formality_level': 'informal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_price',
               'lang_code': 'id',
               'keyword': 'tarif per bulan',
               'normalized_keyword': 'tarif bulanan',
               'formality_level': 'formal',
               'weight': 4,
               'notes': None},
              {'intent_code': 'ask_price',
               'lang_code': 'id',
               'keyword': 'langganannya berapa sebulan?',
               'normalized_keyword': 'langganan bulanan',
               'formality_level': 'informal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_price',
               'lang_code': 'id',
               'keyword': 'ada harga promo?',
               'normalized_keyword': 'harga promo',
               'formality_level': 'informal',
               'weight': 4,
               'notes': None},
              {'intent_code': 'ask_price',
               'lang_code': 'id',
               'keyword': 'total biaya awal berapa?',
               'normalized_keyword': 'biaya awal',
               'formality_level': 'semi_formal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_price',
               'lang_code': 'id',
               'keyword': 'berapa biaya internet rumah?',
               'normalized_keyword': 'biaya internet rumah',
               'formality_level': 'semi_formal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_price',
               'lang_code': 'id',
               'keyword': 'paket 20 mbps berapa?',
               'normalized_keyword': 'harga speed',
               'formality_level': 'informal',
               'weight': 5,
               'notes': 'Contains speed entity'},
              {'intent_code': 'ask_price',
               'lang_code': 'id',
               'keyword': 'harga sudah termasuk modem?',
               'normalized_keyword': 'harga termasuk modem',
               'formality_level': 'semi_formal',
               'weight': 4,
               'notes': None},
              {'intent_code': 'ask_coverage',
               'lang_code': 'id',
               'keyword': 'area saya tercover?',
               'normalized_keyword': 'cek coverage',
               'formality_level': 'informal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_coverage',
               'lang_code': 'id',
               'keyword': 'cek jaringan di alamat saya',
               'normalized_keyword': 'cek jaringan alamat',
               'formality_level': 'semi_formal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_coverage',
               'lang_code': 'id',
               'keyword': 'apakah daerah saya sudah masuk jaringan?',
               'normalized_keyword': 'coverage daerah',
               'formality_level': 'formal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_coverage',
               'lang_code': 'id',
               'keyword': 'di lokasi saya bisa pasang?',
               'normalized_keyword': 'lokasi bisa pasang',
               'formality_level': 'informal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_coverage',
               'lang_code': 'id',
               'keyword': 'coverage di Bandung ada?',
               'normalized_keyword': 'coverage area',
               'formality_level': 'informal',
               'weight': 4,
               'notes': 'Area entity'},
              {'intent_code': 'ask_coverage',
               'lang_code': 'id',
               'keyword': 'jaringan sudah sampai sini belum?',
               'normalized_keyword': 'jaringan tersedia',
               'formality_level': 'informal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_coverage',
               'lang_code': 'id',
               'keyword': 'alamat saya bisa dipasang internet?',
               'normalized_keyword': 'alamat bisa pasang',
               'formality_level': 'semi_formal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_coverage',
               'lang_code': 'id',
               'keyword': 'cek coverage dulu',
               'normalized_keyword': 'cek coverage',
               'formality_level': 'informal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_coverage',
               'lang_code': 'id',
               'keyword': 'di komplek saya sudah ada jaringan?',
               'normalized_keyword': 'coverage komplek',
               'formality_level': 'informal',
               'weight': 4,
               'notes': None},
              {'intent_code': 'ask_coverage',
               'lang_code': 'id',
               'keyword': 'apakah layanan tersedia di wilayah saya?',
               'normalized_keyword': 'layanan tersedia wilayah',
               'formality_level': 'formal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_installation_schedule',
               'lang_code': 'id',
               'keyword': 'kapan bisa dipasang?',
               'normalized_keyword': 'jadwal pemasangan',
               'formality_level': 'informal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_installation_schedule',
               'lang_code': 'id',
               'keyword': 'jadwal teknisi kapan?',
               'normalized_keyword': 'jadwal teknisi',
               'formality_level': 'informal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_installation_schedule',
               'lang_code': 'id',
               'keyword': 'bisa pasang hari ini?',
               'normalized_keyword': 'pasang hari ini',
               'formality_level': 'informal',
               'weight': 5,
               'notes': 'Urgent'},
              {'intent_code': 'ask_installation_schedule',
               'lang_code': 'id',
               'keyword': 'pemasangan bisa besok?',
               'normalized_keyword': 'pasang besok',
               'formality_level': 'informal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_installation_schedule',
               'lang_code': 'id',
               'keyword': 'saya ingin jadwalkan pemasangan',
               'normalized_keyword': 'jadwalkan pemasangan',
               'formality_level': 'formal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_installation_schedule',
               'lang_code': 'id',
               'keyword': 'teknisi bisa datang jam berapa?',
               'normalized_keyword': 'jam teknisi datang',
               'formality_level': 'semi_formal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_installation_schedule',
               'lang_code': 'id',
               'keyword': 'berapa lama proses pemasangan?',
               'normalized_keyword': 'durasi pemasangan',
               'formality_level': 'semi_formal',
               'weight': 4,
               'notes': None},
              {'intent_code': 'ask_installation_schedule',
               'lang_code': 'id',
               'keyword': 'estimasi pemasangan berapa hari?',
               'normalized_keyword': 'estimasi pemasangan',
               'formality_level': 'semi_formal',
               'weight': 4,
               'notes': None},
              {'intent_code': 'ask_installation_schedule',
               'lang_code': 'id',
               'keyword': 'bisa request jadwal?',
               'normalized_keyword': 'request jadwal',
               'formality_level': 'informal',
               'weight': 4,
               'notes': None},
              {'intent_code': 'ask_installation_schedule',
               'lang_code': 'id',
               'keyword': 'saya available hari sabtu',
               'normalized_keyword': 'available schedule',
               'formality_level': 'semi_formal',
               'weight': 4,
               'notes': None},
              {'intent_code': 'ask_payment_method',
               'lang_code': 'id',
               'keyword': 'bayarnya gimana?',
               'normalized_keyword': 'cara bayar',
               'formality_level': 'informal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_payment_method',
               'lang_code': 'id',
               'keyword': 'metode pembayaran apa saja?',
               'normalized_keyword': 'metode pembayaran',
               'formality_level': 'formal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_payment_method',
               'lang_code': 'id',
               'keyword': 'bisa bayar transfer?',
               'normalized_keyword': 'bayar transfer',
               'formality_level': 'informal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_payment_method',
               'lang_code': 'id',
               'keyword': 'bisa bayar cash?',
               'normalized_keyword': 'bayar cash',
               'formality_level': 'informal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_payment_method',
               'lang_code': 'id',
               'keyword': 'ada qris?',
               'normalized_keyword': 'qris',
               'formality_level': 'informal',
               'weight': 4,
               'notes': None},
              {'intent_code': 'ask_payment_method',
               'lang_code': 'id',
               'keyword': 'pembayaran lewat virtual account bisa?',
               'normalized_keyword': 'virtual account',
               'formality_level': 'formal',
               'weight': 4,
               'notes': None},
              {'intent_code': 'ask_payment_method',
               'lang_code': 'id',
               'keyword': 'bayar setelah terpasang?',
               'normalized_keyword': 'bayar setelah pasang',
               'formality_level': 'informal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_payment_method',
               'lang_code': 'id',
               'keyword': 'harus bayar dulu?',
               'normalized_keyword': 'bayar dulu',
               'formality_level': 'informal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_payment_method',
               'lang_code': 'id',
               'keyword': 'tagihan dibayar ke mana?',
               'normalized_keyword': 'bayar tagihan',
               'formality_level': 'semi_formal',
               'weight': 4,
               'notes': None},
              {'intent_code': 'ask_payment_method',
               'lang_code': 'id',
               'keyword': 'bisa pakai e-wallet?',
               'normalized_keyword': 'e-wallet',
               'formality_level': 'informal',
               'weight': 4,
               'notes': None},
              {'intent_code': 'ask_installation',
               'lang_code': 'su',
               'keyword': 'abdi hoyong pasang internet',
               'normalized_keyword': 'pasang internet',
               'formality_level': 'formal',
               'weight': 5,
               'notes': 'Sundanese polite'},
              {'intent_code': 'ask_installation',
               'lang_code': 'su',
               'keyword': 'rek masang wifi di bumi',
               'normalized_keyword': 'pasang wifi rumah',
               'formality_level': 'informal',
               'weight': 5,
               'notes': 'Mixed informal'},
              {'intent_code': 'ask_installation',
               'lang_code': 'su',
               'keyword': 'bisa pasang wifi di imah?',
               'normalized_keyword': 'pasang wifi rumah',
               'formality_level': 'informal',
               'weight': 5,
               'notes': 'Common mixed'},
              {'intent_code': 'ask_installation',
               'lang_code': 'su',
               'keyword': 'abdi bade langganan internet',
               'normalized_keyword': 'langganan internet',
               'formality_level': 'formal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_installation',
               'lang_code': 'su',
               'keyword': 'hoyong daftar internet bumi',
               'normalized_keyword': 'daftar internet rumah',
               'formality_level': 'semi_formal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_installation',
               'lang_code': 'su',
               'keyword': 'aya layanan internet kanggo bumi?',
               'normalized_keyword': 'layanan internet rumah',
               'formality_level': 'semi_formal',
               'weight': 4,
               'notes': None},
              {'intent_code': 'ask_installation',
               'lang_code': 'su',
               'keyword': 'kumaha carana masang wifi?',
               'normalized_keyword': 'cara pasang wifi',
               'formality_level': 'informal',
               'weight': 4,
               'notes': None},
              {'intent_code': 'ask_installation',
               'lang_code': 'su',
               'keyword': 'abdi minat pasang internet',
               'normalized_keyword': 'minat pasang internet',
               'formality_level': 'formal',
               'weight': 4,
               'notes': None},
              {'intent_code': 'ask_installation',
               'lang_code': 'su',
               'keyword': 'di bumi abdi tiasa dipasang wifi?',
               'normalized_keyword': 'rumah bisa pasang wifi',
               'formality_level': 'formal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_installation',
               'lang_code': 'su',
               'keyword': 'rek daftar wifi kang',
               'normalized_keyword': 'daftar wifi',
               'formality_level': 'informal',
               'weight': 5,
               'notes': 'Very common sales chat'},
              {'intent_code': 'ask_package',
               'lang_code': 'su',
               'keyword': 'paketna aya naon wae?',
               'normalized_keyword': 'paket tersedia',
               'formality_level': 'informal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_package',
               'lang_code': 'su',
               'keyword': 'aya paket internet naon wae?',
               'normalized_keyword': 'paket internet tersedia',
               'formality_level': 'semi_formal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_package',
               'lang_code': 'su',
               'keyword': 'muhun, paket wifi na naon wae?',
               'normalized_keyword': 'paket wifi tersedia',
               'formality_level': 'semi_formal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_package',
               'lang_code': 'su',
               'keyword': 'paket anu paling mirah naon?',
               'normalized_keyword': 'paket murah',
               'formality_level': 'informal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_package',
               'lang_code': 'su',
               'keyword': 'abdi tiasa ningali daftar paket?',
               'normalized_keyword': 'daftar paket',
               'formality_level': 'formal',
               'weight': 4,
               'notes': None},
              {'intent_code': 'ask_package',
               'lang_code': 'su',
               'keyword': 'paket kanggo bumi aya?',
               'normalized_keyword': 'paket rumah',
               'formality_level': 'semi_formal',
               'weight': 4,
               'notes': None},
              {'intent_code': 'ask_package',
               'lang_code': 'su',
               'keyword': 'aya paket unlimited?',
               'normalized_keyword': 'paket unlimited',
               'formality_level': 'informal',
               'weight': 4,
               'notes': None},
              {'intent_code': 'ask_package',
               'lang_code': 'su',
               'keyword': 'paket 20 mega aya?',
               'normalized_keyword': 'paket speed',
               'formality_level': 'informal',
               'weight': 4,
               'notes': 'Speed entity'},
              {'intent_code': 'ask_package',
               'lang_code': 'su',
               'keyword': 'paket keluarga aya teu?',
               'normalized_keyword': 'paket keluarga',
               'formality_level': 'informal',
               'weight': 3,
               'notes': None},
              {'intent_code': 'ask_package',
               'lang_code': 'su',
               'keyword': 'minta info paketna kang',
               'normalized_keyword': 'info paket',
               'formality_level': 'informal',
               'weight': 5,
               'notes': 'Mixed'},
              {'intent_code': 'ask_price',
               'lang_code': 'su',
               'keyword': 'sabaraha hargana?',
               'normalized_keyword': 'harga',
               'formality_level': 'informal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_price',
               'lang_code': 'su',
               'keyword': 'biayana sabaraha?',
               'normalized_keyword': 'biaya',
               'formality_level': 'semi_formal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_price',
               'lang_code': 'su',
               'keyword': 'sabulan sabaraha?',
               'normalized_keyword': 'biaya bulanan',
               'formality_level': 'informal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_price',
               'lang_code': 'su',
               'keyword': 'tarif per bulan sabaraha?',
               'normalized_keyword': 'tarif bulanan',
               'formality_level': 'semi_formal',
               'weight': 4,
               'notes': None},
              {'intent_code': 'ask_price',
               'lang_code': 'su',
               'keyword': 'harga paketna sabaraha?',
               'normalized_keyword': 'harga paket',
               'formality_level': 'informal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_price',
               'lang_code': 'su',
               'keyword': 'aya promo harga?',
               'normalized_keyword': 'harga promo',
               'formality_level': 'informal',
               'weight': 4,
               'notes': None},
              {'intent_code': 'ask_price',
               'lang_code': 'su',
               'keyword': 'biaya awalna sabaraha?',
               'normalized_keyword': 'biaya awal',
               'formality_level': 'semi_formal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_price',
               'lang_code': 'su',
               'keyword': 'pemasangan kedah mayar sabaraha?',
               'normalized_keyword': 'biaya pemasangan',
               'formality_level': 'formal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_price',
               'lang_code': 'su',
               'keyword': 'paket 30 mbps sabaraha?',
               'normalized_keyword': 'harga speed',
               'formality_level': 'informal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_price',
               'lang_code': 'su',
               'keyword': 'harga tos kaasup modem?',
               'normalized_keyword': 'harga termasuk modem',
               'formality_level': 'semi_formal',
               'weight': 4,
               'notes': None},
              {'intent_code': 'ask_coverage',
               'lang_code': 'su',
               'keyword': 'di daerah abdi tos aya jaringan?',
               'normalized_keyword': 'coverage daerah',
               'formality_level': 'formal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_coverage',
               'lang_code': 'su',
               'keyword': 'alamat abdi tiasa dipasang?',
               'normalized_keyword': 'alamat bisa pasang',
               'formality_level': 'formal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_coverage',
               'lang_code': 'su',
               'keyword': 'di imah abdi bisa pasang wifi?',
               'normalized_keyword': 'rumah bisa pasang wifi',
               'formality_level': 'semi_formal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_coverage',
               'lang_code': 'su',
               'keyword': 'cek jaringan di alamat ieu',
               'normalized_keyword': 'cek jaringan alamat',
               'formality_level': 'informal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_coverage',
               'lang_code': 'su',
               'keyword': 'daerah abdi ka-cover teu?',
               'normalized_keyword': 'coverage area',
               'formality_level': 'informal',
               'weight': 5,
               'notes': 'Mixed'},
              {'intent_code': 'ask_coverage',
               'lang_code': 'su',
               'keyword': 'di komplek abdi tos aya jaringan?',
               'normalized_keyword': 'coverage komplek',
               'formality_level': 'semi_formal',
               'weight': 4,
               'notes': None},
              {'intent_code': 'ask_coverage',
               'lang_code': 'su',
               'keyword': 'jaringan tos dugi ka dieu acan?',
               'normalized_keyword': 'jaringan tersedia',
               'formality_level': 'informal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_coverage',
               'lang_code': 'su',
               'keyword': 'wilayah ieu tiasa dipasang internet?',
               'normalized_keyword': 'wilayah bisa pasang',
               'formality_level': 'semi_formal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_coverage',
               'lang_code': 'su',
               'keyword': 'kanggo alamat ieu aya coverage?',
               'normalized_keyword': 'coverage alamat',
               'formality_level': 'semi_formal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_coverage',
               'lang_code': 'su',
               'keyword': 'bisa cek coverage heula?',
               'normalized_keyword': 'cek coverage',
               'formality_level': 'informal',
               'weight': 5,
               'notes': 'Mixed'},
              {'intent_code': 'ask_installation',
               'lang_code': 'en',
               'keyword': 'I want to install home internet',
               'normalized_keyword': 'install home internet',
               'formality_level': 'formal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_installation',
               'lang_code': 'en',
               'keyword': 'can I install wifi at home?',
               'normalized_keyword': 'install wifi home',
               'formality_level': 'informal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_installation',
               'lang_code': 'en',
               'keyword': 'I would like to subscribe to home internet',
               'normalized_keyword': 'subscribe home internet',
               'formality_level': 'formal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_installation',
               'lang_code': 'en',
               'keyword': 'how can I get wifi installed?',
               'normalized_keyword': 'get wifi installed',
               'formality_level': 'semi_formal',
               'weight': 4,
               'notes': None},
              {'intent_code': 'ask_installation',
               'lang_code': 'en',
               'keyword': 'I want to register for internet service',
               'normalized_keyword': 'register internet service',
               'formality_level': 'formal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_installation',
               'lang_code': 'en',
               'keyword': 'do you provide home internet?',
               'normalized_keyword': 'provide home internet',
               'formality_level': 'semi_formal',
               'weight': 4,
               'notes': None},
              {'intent_code': 'ask_installation',
               'lang_code': 'en',
               'keyword': 'need wifi installation',
               'normalized_keyword': 'wifi installation',
               'formality_level': 'informal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_installation',
               'lang_code': 'en',
               'keyword': 'can you install internet in my house?',
               'normalized_keyword': 'install internet house',
               'formality_level': 'informal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_installation',
               'lang_code': 'en',
               'keyword': 'I am interested in your internet service',
               'normalized_keyword': 'interested internet service',
               'formality_level': 'formal',
               'weight': 4,
               'notes': None},
              {'intent_code': 'ask_installation',
               'lang_code': 'en',
               'keyword': 'how do I apply for home broadband?',
               'normalized_keyword': 'apply home broadband',
               'formality_level': 'formal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_package',
               'lang_code': 'en',
               'keyword': 'what packages are available?',
               'normalized_keyword': 'available packages',
               'formality_level': 'semi_formal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_package',
               'lang_code': 'en',
               'keyword': 'what internet plans do you have?',
               'normalized_keyword': 'internet plans',
               'formality_level': 'informal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_package',
               'lang_code': 'en',
               'keyword': 'can I see the package list?',
               'normalized_keyword': 'package list',
               'formality_level': 'semi_formal',
               'weight': 4,
               'notes': None},
              {'intent_code': 'ask_package',
               'lang_code': 'en',
               'keyword': 'do you have unlimited plans?',
               'normalized_keyword': 'unlimited plans',
               'formality_level': 'informal',
               'weight': 4,
               'notes': None},
              {'intent_code': 'ask_package',
               'lang_code': 'en',
               'keyword': 'what is the cheapest package?',
               'normalized_keyword': 'cheapest package',
               'formality_level': 'informal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_package',
               'lang_code': 'en',
               'keyword': 'home wifi package',
               'normalized_keyword': 'home wifi package',
               'formality_level': 'informal',
               'weight': 4,
               'notes': None},
              {'intent_code': 'ask_package',
               'lang_code': 'en',
               'keyword': 'family internet package',
               'normalized_keyword': 'family internet package',
               'formality_level': 'semi_formal',
               'weight': 3,
               'notes': None},
              {'intent_code': 'ask_package',
               'lang_code': 'en',
               'keyword': 'which plan is suitable for home use?',
               'normalized_keyword': 'suitable home plan',
               'formality_level': 'semi_formal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_package',
               'lang_code': 'en',
               'keyword': 'do you have a gaming package?',
               'normalized_keyword': 'gaming package',
               'formality_level': 'informal',
               'weight': 3,
               'notes': None},
              {'intent_code': 'ask_package',
               'lang_code': 'en',
               'keyword': 'please send me the internet package details',
               'normalized_keyword': 'package details',
               'formality_level': 'formal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_price',
               'lang_code': 'en',
               'keyword': 'how much is it?',
               'normalized_keyword': 'price',
               'formality_level': 'informal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_price',
               'lang_code': 'en',
               'keyword': 'what is the monthly fee?',
               'normalized_keyword': 'monthly fee',
               'formality_level': 'semi_formal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_price',
               'lang_code': 'en',
               'keyword': 'how much per month?',
               'normalized_keyword': 'monthly price',
               'formality_level': 'informal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_price',
               'lang_code': 'en',
               'keyword': 'what is the subscription cost?',
               'normalized_keyword': 'subscription cost',
               'formality_level': 'formal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_price',
               'lang_code': 'en',
               'keyword': 'is there any promo price?',
               'normalized_keyword': 'promo price',
               'formality_level': 'informal',
               'weight': 4,
               'notes': None},
              {'intent_code': 'ask_price',
               'lang_code': 'en',
               'keyword': 'how much is the installation fee?',
               'normalized_keyword': 'installation fee',
               'formality_level': 'semi_formal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_price',
               'lang_code': 'en',
               'keyword': 'what is the total upfront cost?',
               'normalized_keyword': 'upfront cost',
               'formality_level': 'formal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_price',
               'lang_code': 'en',
               'keyword': 'does the price include the router?',
               'normalized_keyword': 'price include router',
               'formality_level': 'semi_formal',
               'weight': 4,
               'notes': None},
              {'intent_code': 'ask_price',
               'lang_code': 'en',
               'keyword': 'how much for 30 mbps?',
               'normalized_keyword': 'price speed',
               'formality_level': 'informal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_price',
               'lang_code': 'en',
               'keyword': 'are there any additional charges?',
               'normalized_keyword': 'additional charges',
               'formality_level': 'formal',
               'weight': 4,
               'notes': None},
              {'intent_code': 'ask_coverage',
               'lang_code': 'en',
               'keyword': 'is my area covered?',
               'normalized_keyword': 'area coverage',
               'formality_level': 'informal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_coverage',
               'lang_code': 'en',
               'keyword': 'can you check coverage at my address?',
               'normalized_keyword': 'check coverage address',
               'formality_level': 'semi_formal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_coverage',
               'lang_code': 'en',
               'keyword': 'is your network available in my area?',
               'normalized_keyword': 'network available area',
               'formality_level': 'formal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_coverage',
               'lang_code': 'en',
               'keyword': 'can I install it at my location?',
               'normalized_keyword': 'install location',
               'formality_level': 'informal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_coverage',
               'lang_code': 'en',
               'keyword': 'do you cover this address?',
               'normalized_keyword': 'cover address',
               'formality_level': 'semi_formal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_coverage',
               'lang_code': 'en',
               'keyword': 'is there service in my neighborhood?',
               'normalized_keyword': 'service neighborhood',
               'formality_level': 'semi_formal',
               'weight': 4,
               'notes': None},
              {'intent_code': 'ask_coverage',
               'lang_code': 'en',
               'keyword': 'can you check my address first?',
               'normalized_keyword': 'check address',
               'formality_level': 'informal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_coverage',
               'lang_code': 'en',
               'keyword': 'is broadband available here?',
               'normalized_keyword': 'broadband available',
               'formality_level': 'semi_formal',
               'weight': 4,
               'notes': None},
              {'intent_code': 'ask_coverage',
               'lang_code': 'en',
               'keyword': 'does your fiber network reach my house?',
               'normalized_keyword': 'fiber network reach house',
               'formality_level': 'formal',
               'weight': 5,
               'notes': None},
              {'intent_code': 'ask_coverage',
               'lang_code': 'en',
               'keyword': 'coverage check please',
               'normalized_keyword': 'coverage check',
               'formality_level': 'informal',
               'weight': 5,
               'notes': None}],
 'entity_keywords': [{'entity_code': 'speed',
                      'lang_code': 'id',
                      'keyword': '10 mbps',
                      'normalized_keyword': '10 mbps',
                      'notes': None},
                     {'entity_code': 'speed',
                      'lang_code': 'id',
                      'keyword': '20 mbps',
                      'normalized_keyword': '20 mbps',
                      'notes': None},
                     {'entity_code': 'speed',
                      'lang_code': 'id',
                      'keyword': '30 mbps',
                      'normalized_keyword': '30 mbps',
                      'notes': None},
                     {'entity_code': 'speed',
                      'lang_code': 'id',
                      'keyword': '50 mbps',
                      'normalized_keyword': '50 mbps',
                      'notes': None},
                     {'entity_code': 'speed',
                      'lang_code': 'id',
                      'keyword': '100 mbps',
                      'normalized_keyword': '100 mbps',
                      'notes': None},
                     {'entity_code': 'speed',
                      'lang_code': 'id',
                      'keyword': '1 gbps',
                      'normalized_keyword': '1 gbps',
                      'notes': None},
                     {'entity_code': 'speed',
                      'lang_code': 'id',
                      'keyword': '10 mega',
                      'normalized_keyword': '10 mbps',
                      'notes': 'Colloquial'},
                     {'entity_code': 'speed',
                      'lang_code': 'id',
                      'keyword': '20 mega',
                      'normalized_keyword': '20 mbps',
                      'notes': 'Colloquial'},
                     {'entity_code': 'speed',
                      'lang_code': 'id',
                      'keyword': '30 mega',
                      'normalized_keyword': '30 mbps',
                      'notes': 'Colloquial'},
                     {'entity_code': 'speed',
                      'lang_code': 'id',
                      'keyword': '50 mega',
                      'normalized_keyword': '50 mbps',
                      'notes': 'Colloquial'},
                     {'entity_code': 'payment_method',
                      'lang_code': 'id',
                      'keyword': 'transfer bank',
                      'normalized_keyword': 'bank_transfer',
                      'notes': None},
                     {'entity_code': 'payment_method',
                      'lang_code': 'id',
                      'keyword': 'transfer',
                      'normalized_keyword': 'bank_transfer',
                      'notes': None},
                     {'entity_code': 'payment_method',
                      'lang_code': 'id',
                      'keyword': 'qris',
                      'normalized_keyword': 'qris',
                      'notes': None},
                     {'entity_code': 'payment_method',
                      'lang_code': 'id',
                      'keyword': 'cash',
                      'normalized_keyword': 'cash',
                      'notes': None},
                     {'entity_code': 'payment_method',
                      'lang_code': 'id',
                      'keyword': 'tunai',
                      'normalized_keyword': 'cash',
                      'notes': None},
                     {'entity_code': 'payment_method',
                      'lang_code': 'id',
                      'keyword': 'virtual account',
                      'normalized_keyword': 'virtual_account',
                      'notes': None},
                     {'entity_code': 'payment_method',
                      'lang_code': 'id',
                      'keyword': 'e-wallet',
                      'normalized_keyword': 'e_wallet',
                      'notes': None},
                     {'entity_code': 'payment_method',
                      'lang_code': 'id',
                      'keyword': 'gopay',
                      'normalized_keyword': 'gopay',
                      'notes': None},
                     {'entity_code': 'payment_method',
                      'lang_code': 'id',
                      'keyword': 'ovo',
                      'normalized_keyword': 'ovo',
                      'notes': None},
                     {'entity_code': 'payment_method',
                      'lang_code': 'id',
                      'keyword': 'dana',
                      'normalized_keyword': 'dana',
                      'notes': None},
                     {'entity_code': 'router',
                      'lang_code': 'id',
                      'keyword': 'modem',
                      'normalized_keyword': 'modem',
                      'notes': None},
                     {'entity_code': 'router',
                      'lang_code': 'id',
                      'keyword': 'router',
                      'normalized_keyword': 'router',
                      'notes': None},
                     {'entity_code': 'router',
                      'lang_code': 'id',
                      'keyword': 'wifi router',
                      'normalized_keyword': 'router',
                      'notes': None},
                     {'entity_code': 'router',
                      'lang_code': 'id',
                      'keyword': 'ont',
                      'normalized_keyword': 'ont',
                      'notes': 'Fiber device'},
                     {'entity_code': 'router',
                      'lang_code': 'id',
                      'keyword': 'perangkat wifi',
                      'normalized_keyword': 'router',
                      'notes': None},
                     {'entity_code': 'schedule_time',
                      'lang_code': 'id',
                      'keyword': 'pagi',
                      'normalized_keyword': 'morning',
                      'notes': None},
                     {'entity_code': 'schedule_time',
                      'lang_code': 'id',
                      'keyword': 'siang',
                      'normalized_keyword': 'afternoon',
                      'notes': None},
                     {'entity_code': 'schedule_time',
                      'lang_code': 'id',
                      'keyword': 'sore',
                      'normalized_keyword': 'evening',
                      'notes': None},
                     {'entity_code': 'schedule_time',
                      'lang_code': 'id',
                      'keyword': 'malam',
                      'normalized_keyword': 'night',
                      'notes': None},
                     {'entity_code': 'schedule_time',
                      'lang_code': 'id',
                      'keyword': 'jam 9',
                      'normalized_keyword': '09:00',
                      'notes': None},
                     {'entity_code': 'schedule_time',
                      'lang_code': 'id',
                      'keyword': 'jam 10',
                      'normalized_keyword': '10:00',
                      'notes': None},
                     {'entity_code': 'schedule_time',
                      'lang_code': 'id',
                      'keyword': 'jam 1 siang',
                      'normalized_keyword': '13:00',
                      'notes': None},
                     {'entity_code': 'schedule_date',
                      'lang_code': 'id',
                      'keyword': 'hari ini',
                      'normalized_keyword': 'today',
                      'notes': None},
                     {'entity_code': 'schedule_date',
                      'lang_code': 'id',
                      'keyword': 'besok',
                      'normalized_keyword': 'tomorrow',
                      'notes': None},
                     {'entity_code': 'schedule_date',
                      'lang_code': 'id',
                      'keyword': 'lusa',
                      'normalized_keyword': 'day_after_tomorrow',
                      'notes': None},
                     {'entity_code': 'schedule_date',
                      'lang_code': 'id',
                      'keyword': 'sabtu',
                      'normalized_keyword': 'saturday',
                      'notes': None},
                     {'entity_code': 'schedule_date',
                      'lang_code': 'id',
                      'keyword': 'minggu',
                      'normalized_keyword': 'sunday',
                      'notes': None},
                     {'entity_code': 'schedule_date',
                      'lang_code': 'id',
                      'keyword': 'weekday',
                      'normalized_keyword': 'weekday',
                      'notes': None},
                     {'entity_code': 'schedule_date',
                      'lang_code': 'id',
                      'keyword': 'weekend',
                      'normalized_keyword': 'weekend',
                      'notes': None}],
 'sample_utterances': [{'intent_code': 'ask_installation',
                        'lang_code': 'id',
                        'utterance': 'Halo kak, saya mau pasang internet di rumah, bisa dibantu?',
                        'formality_level': 'semi_formal',
                        'expected_entities': '{}',
                        'notes': None},
                       {'intent_code': 'ask_installation',
                        'lang_code': 'id',
                        'utterance': 'Kang, mau pasang wifi rumah nih',
                        'formality_level': 'informal',
                        'expected_entities': '{}',
                        'notes': None},
                       {'intent_code': 'ask_package',
                        'lang_code': 'id',
                        'utterance': 'Paket internet rumahnya ada apa saja ya?',
                        'formality_level': 'semi_formal',
                        'expected_entities': '{}',
                        'notes': None},
                       {'intent_code': 'ask_price',
                        'lang_code': 'id',
                        'utterance': 'Kalau paket 30 Mbps berapa per bulan?',
                        'formality_level': 'informal',
                        'expected_entities': '{"speed":"30 Mbps"}',
                        'notes': None},
                       {'intent_code': 'ask_coverage',
                        'lang_code': 'id',
                        'utterance': 'Alamat saya di Cibiru, apakah sudah tercover jaringan?',
                        'formality_level': 'semi_formal',
                        'expected_entities': '{"area":"Cibiru"}',
                        'notes': None},
                       {'intent_code': 'ask_installation_schedule',
                        'lang_code': 'id',
                        'utterance': 'Kalau daftar sekarang, teknisi bisa datang kapan?',
                        'formality_level': 'semi_formal',
                        'expected_entities': '{}',
                        'notes': None},
                       {'intent_code': 'ask_payment_method',
                        'lang_code': 'id',
                        'utterance': 'Pembayarannya bisa pakai QRIS atau transfer?',
                        'formality_level': 'informal',
                        'expected_entities': '{"payment_method":["qris","bank_transfer"]}',
                        'notes': None},
                       {'intent_code': 'choose_package',
                        'lang_code': 'id',
                        'utterance': 'Saya ambil paket 50 Mbps saja',
                        'formality_level': 'semi_formal',
                        'expected_entities': '{"speed":"50 Mbps"}',
                        'notes': None},
                       {'intent_code': 'confirm_order',
                        'lang_code': 'id',
                        'utterance': 'Oke kak, saya jadi pasang. Tolong proses ya',
                        'formality_level': 'semi_formal',
                        'expected_entities': '{}',
                        'notes': None},
                       {'intent_code': 'follow_up_installation',
                        'lang_code': 'id',
                        'utterance': 'Teknisinya sudah sampai mana ya? Saya sudah menunggu dari '
                                     'pagi',
                        'formality_level': 'semi_formal',
                        'expected_entities': '{"schedule_time":"morning"}',
                        'notes': None},
                       {'intent_code': 'ask_installation',
                        'lang_code': 'su',
                        'utterance': 'Kang, abdi hoyong pasang internet di bumi',
                        'formality_level': 'semi_formal',
                        'expected_entities': '{}',
                        'notes': None},
                       {'intent_code': 'ask_installation',
                        'lang_code': 'su',
                        'utterance': 'Rek masang wifi di imah, bisa?',
                        'formality_level': 'informal',
                        'expected_entities': '{}',
                        'notes': None},
                       {'intent_code': 'ask_package',
                        'lang_code': 'su',
                        'utterance': 'Paketna aya naon wae kang?',
                        'formality_level': 'informal',
                        'expected_entities': '{}',
                        'notes': None},
                       {'intent_code': 'ask_price',
                        'lang_code': 'su',
                        'utterance': 'Paket 30 Mbps sabaraha sabulan?',
                        'formality_level': 'informal',
                        'expected_entities': '{"speed":"30 Mbps"}',
                        'notes': None},
                       {'intent_code': 'ask_coverage',
                        'lang_code': 'su',
                        'utterance': 'Di daerah Cibiru tos aya jaringan?',
                        'formality_level': 'semi_formal',
                        'expected_entities': '{"area":"Cibiru"}',
                        'notes': None},
                       {'intent_code': 'ask_installation_schedule',
                        'lang_code': 'su',
                        'utterance': 'Teknisi tiasa sumping iraha?',
                        'formality_level': 'formal',
                        'expected_entities': '{}',
                        'notes': None},
                       {'intent_code': 'ask_payment_method',
                        'lang_code': 'su',
                        'utterance': 'Bayarna tiasa transfer atanapi QRIS?',
                        'formality_level': 'semi_formal',
                        'expected_entities': '{"payment_method":["bank_transfer","qris"]}',
                        'notes': None},
                       {'intent_code': 'choose_package',
                        'lang_code': 'su',
                        'utterance': 'Abdi pilih paket 50 Mbps wae',
                        'formality_level': 'semi_formal',
                        'expected_entities': '{"speed":"50 Mbps"}',
                        'notes': None},
                       {'intent_code': 'confirm_order',
                        'lang_code': 'su',
                        'utterance': 'Muhun, abdi jadi pasang. Punten diproses',
                        'formality_level': 'formal',
                        'expected_entities': '{}',
                        'notes': None},
                       {'intent_code': 'follow_up_installation',
                        'lang_code': 'su',
                        'utterance': 'Kang, teknisina tos dugi mana? Abdi tos ngantosan',
                        'formality_level': 'informal',
                        'expected_entities': '{}',
                        'notes': None},
                       {'intent_code': 'ask_installation',
                        'lang_code': 'en',
                        'utterance': 'Hi, I want to install home internet. Can you help me?',
                        'formality_level': 'semi_formal',
                        'expected_entities': '{}',
                        'notes': None},
                       {'intent_code': 'ask_installation',
                        'lang_code': 'en',
                        'utterance': 'I need wifi installed at my house',
                        'formality_level': 'informal',
                        'expected_entities': '{}',
                        'notes': None},
                       {'intent_code': 'ask_package',
                        'lang_code': 'en',
                        'utterance': 'What internet packages do you have?',
                        'formality_level': 'informal',
                        'expected_entities': '{}',
                        'notes': None},
                       {'intent_code': 'ask_price',
                        'lang_code': 'en',
                        'utterance': 'How much is the 30 Mbps plan per month?',
                        'formality_level': 'semi_formal',
                        'expected_entities': '{"speed":"30 Mbps"}',
                        'notes': None},
                       {'intent_code': 'ask_coverage',
                        'lang_code': 'en',
                        'utterance': 'Can you check if my address is covered?',
                        'formality_level': 'semi_formal',
                        'expected_entities': '{}',
                        'notes': None},
                       {'intent_code': 'ask_installation_schedule',
                        'lang_code': 'en',
                        'utterance': 'If I register today, when can the technician come?',
                        'formality_level': 'semi_formal',
                        'expected_entities': '{}',
                        'notes': None},
                       {'intent_code': 'ask_payment_method',
                        'lang_code': 'en',
                        'utterance': 'Can I pay by bank transfer or QRIS?',
                        'formality_level': 'semi_formal',
                        'expected_entities': '{"payment_method":["bank_transfer","qris"]}',
                        'notes': None},
                       {'intent_code': 'choose_package',
                        'lang_code': 'en',
                        'utterance': 'I will take the 50 Mbps package',
                        'formality_level': 'semi_formal',
                        'expected_entities': '{"speed":"50 Mbps"}',
                        'notes': None},
                       {'intent_code': 'confirm_order',
                        'lang_code': 'en',
                        'utterance': 'Okay, please proceed with the installation',
                        'formality_level': 'formal',
                        'expected_entities': '{}',
                        'notes': None},
                       {'intent_code': 'follow_up_installation',
                        'lang_code': 'en',
                        'utterance': 'Where is the technician now? I have been waiting since '
                                     'morning',
                        'formality_level': 'semi_formal',
                        'expected_entities': '{"schedule_time":"morning"}',
                        'notes': None}],
 'normalization_rules': [{'lang_code': 'id',
                          'source_text': 'inet',
                          'normalized_text': 'internet',
                          'notes': 'slang'},
                         {'lang_code': 'id',
                          'source_text': 'net',
                          'normalized_text': 'internet',
                          'notes': 'slang'},
                         {'lang_code': 'id',
                          'source_text': 'wifi',
                          'normalized_text': 'WiFi',
                          'notes': 'standardization'},
                         {'lang_code': 'id',
                          'source_text': 'wi-fi',
                          'normalized_text': 'WiFi',
                          'notes': 'standardization'},
                         {'lang_code': 'id',
                          'source_text': 'tf',
                          'normalized_text': 'transfer',
                          'notes': 'payment slang'},
                         {'lang_code': 'id',
                          'source_text': 'brp',
                          'normalized_text': 'berapa',
                          'notes': 'question slang'},
                         {'lang_code': 'id',
                          'source_text': 'berapaan',
                          'normalized_text': 'berapa',
                          'notes': 'question slang'},
                         {'lang_code': 'id',
                          'source_text': 'ga',
                          'normalized_text': 'tidak',
                          'notes': 'negation slang'},
                         {'lang_code': 'id',
                          'source_text': 'gak',
                          'normalized_text': 'tidak',
                          'notes': 'negation slang'},
                         {'lang_code': 'id',
                          'source_text': 'udah',
                          'normalized_text': 'sudah',
                          'notes': 'informal'},
                         {'lang_code': 'id',
                          'source_text': 'cover',
                          'normalized_text': 'coverage',
                          'notes': 'coverage synonym'},
                         {'lang_code': 'id',
                          'source_text': 'ka cover',
                          'normalized_text': 'coverage',
                          'notes': 'coverage synonym'},
                         {'lang_code': 'id',
                          'source_text': 'tercover',
                          'normalized_text': 'coverage',
                          'notes': 'coverage synonym'},
                         {'lang_code': 'id',
                          'source_text': '20 mega',
                          'normalized_text': '20 Mbps',
                          'notes': 'speed normalization'},
                         {'lang_code': 'id',
                          'source_text': '30mb',
                          'normalized_text': '30 Mbps',
                          'notes': 'speed normalization'},
                         {'lang_code': 'su',
                          'source_text': 'rek',
                          'normalized_text': 'ingin',
                          'notes': 'Sundanese informal'},
                         {'lang_code': 'su',
                          'source_text': 'hoyong',
                          'normalized_text': 'ingin',
                          'notes': 'Sundanese polite'},
                         {'lang_code': 'su',
                          'source_text': 'bade',
                          'normalized_text': 'ingin',
                          'notes': 'Sundanese polite'},
                         {'lang_code': 'su',
                          'source_text': 'sabaraha',
                          'normalized_text': 'berapa',
                          'notes': 'Sundanese'},
                         {'lang_code': 'su',
                          'source_text': 'iraha',
                          'normalized_text': 'kapan',
                          'notes': 'Sundanese'},
                         {'lang_code': 'su',
                          'source_text': 'imah',
                          'normalized_text': 'rumah',
                          'notes': 'Sundanese informal'},
                         {'lang_code': 'su',
                          'source_text': 'bumi',
                          'normalized_text': 'rumah',
                          'notes': 'Sundanese polite'},
                         {'lang_code': 'su',
                          'source_text': 'tos',
                          'normalized_text': 'sudah',
                          'notes': 'Sundanese'},
                         {'lang_code': 'su',
                          'source_text': 'acan',
                          'normalized_text': 'belum',
                          'notes': 'Sundanese'},
                         {'lang_code': 'en',
                          'source_text': 'wifi',
                          'normalized_text': 'WiFi',
                          'notes': 'standardization'},
                         {'lang_code': 'en',
                          'source_text': 'wi-fi',
                          'normalized_text': 'WiFi',
                          'notes': 'standardization'},
                         {'lang_code': 'en',
                          'source_text': 'broadband',
                          'normalized_text': 'home internet',
                          'notes': 'service synonym'},
                         {'lang_code': 'en',
                          'source_text': 'monthly fee',
                          'normalized_text': 'monthly price',
                          'notes': 'price synonym'},
                         {'lang_code': 'en',
                          'source_text': 'upfront cost',
                          'normalized_text': 'initial cost',
                          'notes': 'price synonym'}]}

DEFAULT_INTENT_MAPPINGS = {'ask_installation': {'description': 'Customer wants to install home internet',
                      'required_slots': ['address', 'customer_name', 'phone_number'],
                      'optional_slots': ['package_name', 'speed', 'schedule_date', 'schedule_time'],
                      'next_action': 'ask_address_or_show_packages'},
 'ask_package': {'description': 'Customer asks available internet packages',
                 'required_slots': [],
                 'optional_slots': ['speed', 'price'],
                 'next_action': 'show_package_list'},
 'ask_price': {'description': 'Customer asks price or monthly subscription fee',
               'required_slots': [],
               'optional_slots': ['speed', 'package_name'],
               'next_action': 'show_price'},
 'ask_coverage': {'description': 'Customer asks network availability',
                  'required_slots': ['address'],
                  'optional_slots': ['area'],
                  'next_action': 'ask_or_validate_address'},
 'ask_installation_schedule': {'description': 'Customer asks installation schedule',
                               'required_slots': ['address', 'package_name'],
                               'optional_slots': ['schedule_date', 'schedule_time'],
                               'next_action': 'check_technician_schedule'},
 'ask_payment_method': {'description': 'Customer asks how to pay',
                        'required_slots': [],
                        'optional_slots': ['payment_method'],
                        'next_action': 'show_payment_methods'},
 'confirm_order': {'description': 'Customer confirms installation order',
                   'required_slots': ['customer_name',
                                      'phone_number',
                                      'address',
                                      'package_name',
                                      'schedule_date'],
                   'optional_slots': ['payment_method'],
                   'next_action': 'create_order'}}
